# Generated by Django 4.2.1 on 2023-08-21 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

import materiah.models.custom_validators


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arrival_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_num',
                 models.CharField(db_index=True, max_length=255, unique=True, verbose_name='catalogue number')),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('category', models.CharField(
                    choices=[('Medium', 'Medium'), ('Powders', 'Powders'), ('Enzymes', 'Enzymes'),
                             ('Plastics', 'Plastics'), ('Glassware', 'Glassware'), ('Sanitary', 'Sanitary'),
                             ('Lab Equipment', 'Lab Equipment')], max_length=255)),
                ('unit', models.CharField(
                    choices=[('ML', 'Milliliters, ml'), ('G', 'Grams, g'), ('MG', 'Milligrams, mg'),
                             ('UG', 'Micrograms, µg'), ('Package', 'Package'), ('Box', 'Box')], max_length=50,
                    verbose_name='measurement unit')),
                ('volume', models.PositiveIntegerField()),
                ('stock', models.PositiveIntegerField()),
                ('storage', models.CharField(
                    choices=[('+4', '+4'), ('-20', '-20'), ('-40', '-40'), ('-80', '-80'), ('Other', 'Other')],
                    max_length=20, verbose_name='storage conditions')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('url', models.URLField()),
                ('manufacturer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiah.manufacturer')),
            ],
        ),
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('website', models.URLField()),
                ('email', models.EmailField(max_length=254)),
                ('phone_prefix',
                 models.CharField(choices=[('02', '02'), ('03', '03'), ('04', '04'), ('08', '08'), ('09', '09')],
                                  default='02', max_length=2)),
                ('phone_suffix',
                 models.CharField(max_length=7, validators=[materiah.models.custom_validators.validate_phone_suffix])),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.CharField(max_length=9, unique=True, validators=[
                    materiah.models.custom_validators.validate_digits_length_and_luhn])),
                ('phone',
                 models.CharField(max_length=10, validators=[materiah.models.custom_validators.validate_phone_suffix])),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierUserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=10, null=True)),
                ('supplier', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materiah.supplier')),
                (
                    'user',
                    models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiah.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiah.quote')),
            ],
        ),
        migrations.AddField(
            model_name='quote',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiah.supplier'),
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiah.supplier'),
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('batch', models.CharField(max_length=50)),
                ('expiry', models.DateField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiah.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiah.product')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiah.quote'),
        ),
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiah.supplier'),
        ),
        migrations.CreateModel(
            name='ManufacturerSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer',
                 models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiah.manufacturer')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiah.supplier')),
            ],
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='suppliers',
            field=models.ManyToManyField(through='materiah.ManufacturerSupplier', to='materiah.supplier'),
        ),
    ]
