# Generated by Django 4.2.1 on 2023-08-21 11:12

from django.db import migrations, models

import materiah.models.custom_validators


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0002_rename_phone_userprofile_phone_suffix_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieruserprofile',
            name='contact_phone',
        ),
        migrations.AddField(
            model_name='supplieruserprofile',
            name='contact_phone_prefix',
            field=models.CharField(blank=True, choices=[('050', '050'), ('051', '051'), ('052', '052'), ('053', '053'),
                                                        ('054', '054'), ('055', '055'), ('056', '056'), ('058', '058'),
                                                        ('059', '059')], default='050', max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='supplieruserprofile',
            name='contact_phone_suffix',
            field=models.CharField(blank=True, max_length=7, null=True,
                                   validators=[materiah.models.custom_validators.validate_phone_suffix]),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='phone_suffix',
            field=models.CharField(max_length=7, validators=[materiah.models.custom_validators.validate_phone_suffix]),
        ),
    ]
