# Generated by Django 4.2.1 on 2023-08-21 11:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0003_remove_supplieruserprofile_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='batch',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='expiry',
            field=models.DateField(blank=True, null=True),
        ),
    ]
