# Generated by Django 4.2.1 on 2023-08-21 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0004_alter_orderitem_batch_alter_orderitem_expiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='pdf',
            field=models.FileField(null=True, upload_to='quotes_pdfs/'),
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiah.product')),
            ],
        ),
    ]
