# Generated by Django 4.2.1 on 2023-09-03 08:55

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0007_userprofile_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='email_verified',
        ),
    ]
