# Generated by Django 4.2.1 on 2023-09-03 10:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0008_remove_userprofile_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieruserprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='supplieruserprofile',
            name='last_name',
        ),
    ]
