# Generated by Django 4.2.1 on 2023-09-03 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0009_remove_supplieruserprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplieruserprofile',
            name='contact_email',
        ),
    ]
