# Generated by Django 4.2.1 on 2023-09-03 19:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0010_remove_supplieruserprofile_contact_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='id_number',
        ),
    ]
