# Generated by Django 4.2.1 on 2023-09-29 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0012_alter_supplier_phone_prefix_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receipt_img',
            field=models.ImageField(null=True, upload_to='order_receipt_images/'),
        ),
        migrations.AddField(
            model_name='quote',
            name='fulfilled',
            field=models.BooleanField(default=False),
        ),
    ]
