# Generated by Django 4.2.1 on 2023-09-29 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0013_order_receipt_img_quote_fulfilled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='supplier',
        ),
    ]
