# Generated by Django 4.2.1 on 2023-09-29 08:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0014_remove_order_supplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product',
        ),
    ]
