# Generated by Django 4.2.1 on 2023-09-29 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0016_orderitem_quote_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='issue_detail',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='status',
            field=models.CharField(
                choices=[('OK', 'OK'), ('Did not arrive', 'Did not arrive'), ('Different amount', 'Different amount'),
                         ('Wrong Item', 'Wrong Item'), ('Expired or near expiry', 'Expired or near expiry'),
                         ('Bad condition', 'Bad condition'), ('Other', 'Other')], default='OK', max_length=22,
                verbose_name='status'),
        ),
    ]
