# Generated by Django 4.2.1 on 2023-10-01 08:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0017_orderitem_issue_detail_orderitem_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='fulfilled',
            field=models.BooleanField(default=True),
        ),
    ]
