# Generated by Django 4.2.1 on 2023-10-01 08:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0018_alter_quote_fulfilled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='fulfilled',
        ),
    ]
