# Generated by Django 4.2.1 on 2023-10-01 08:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0019_remove_quote_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='fufilled',
            field=models.BooleanField(default=True),
        ),
    ]
