# Generated by Django 4.2.1 on 2023-10-01 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0021_rename_fufilled_quote_fulfilled'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='received_by',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
