# Generated by Django 4.2.1 on 2023-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0022_order_received_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
