# Generated by Django 4.2.1 on 2023-10-03 09:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0023_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier_cat_item',
            field=models.BooleanField(default=False),
        ),
    ]
