# Generated by Django 4.2.1 on 2023-10-04 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0024_product_supplier_cat_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='fulfilled',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='pdf',
        ),
        migrations.AddField(
            model_name='quote',
            name='last_updated',
            field=models.DateField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='quote_file',
            field=models.FileField(blank=True, null=True, upload_to='quotes_pdfs/'),
        ),
        migrations.AddField(
            model_name='quote',
            name='request_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='quote',
            name='status',
            field=models.CharField(
                choices=[('REQUESTED', 'Requested'), ('RECEIVED', 'Received'), ('FULFILLED', 'Fulfilled')],
                default='REQUESTED', max_length=10),
        ),
        migrations.AlterField(
            model_name='quote',
            name='creation_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
