# Generated by Django 4.2.1 on 2023-10-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0025_remove_quote_fulfilled_remove_quote_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quoteitem',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
