# Generated by Django 4.2.1 on 2023-10-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0026_alter_quoteitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
