# Generated by Django 4.2.1 on 2023-10-17 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0027_alter_product_price'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('cat_num', 'supplier_cat_item')},
        ),
        migrations.CreateModel(
            name='ProductOrderStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_ordered', models.DateTimeField(blank=True, null=True)),
                ('avg_order_time', models.DurationField(blank=True, null=True)),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='materiah.product')),
            ],
        ),
    ]
