# Generated by Django 4.2.1 on 2023-10-18 08:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0028_alter_product_unique_together_productorderstatistics'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderstatistics',
            name='order_count',
            field=models.IntegerField(default=0),
        ),
    ]
