# Generated by Django 4.2.1 on 2023-10-22 08:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0030_ordernotifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordernotifications',
            name='avg_order_time',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordernotifications',
            name='current_stock',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordernotifications',
            name='last_ordered',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ordernotifications',
            name='product_cat_num',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordernotifications',
            name='product_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='ordernotifications',
            name='supplier_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
