# Generated by Django 4.2.1 on 2023-10-22 11:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0031_ordernotifications_avg_order_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordernotifications',
            name='avg_order_time',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ordernotifications',
            name='last_ordered',
            field=models.DateField(blank=True, null=True),
        ),
    ]
