# Generated by Django 4.2.1 on 2023-10-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0032_alter_ordernotifications_avg_order_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quote',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('RECEIVED', 'Received'),
                                            ('ARRIVED, UNFULFILLED', 'Arrived, unfulfilled'),
                                            ('FULFILLED', 'Fulfilled')], default='REQUESTED', max_length=20),
        ),
    ]
