# Generated by Django 4.2.1 on 2023-10-29 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0033_alter_quote_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cat_num',
            field=models.CharField(db_index=True, max_length=255, verbose_name='catalogue number'),
        ),
    ]
