# Generated by Django 4.2.1 on 2023-10-30 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('materiah', '0034_alter_product_cat_num'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='receipt_img',
        ),
        migrations.CreateModel(
            name='OrderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='orders/')),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiah.order')),
            ],
        ),
    ]
