# Generated by Django 4.2.7 on 2023-11-02 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0036_fileuploadstatus_orderimage_upload_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='image',
        ),
        migrations.AddField(
            model_name='productimage',
            name='s3_image_key',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
