# Generated by Django 4.2.7 on 2023-11-05 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0037_remove_productimage_image_productimage_s3_image_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='image_url',
            field=models.URLField(blank=True, editable=False, max_length=1024),
        ),
    ]
