# Generated by Django 4.2.7 on 2023-11-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0038_productimage_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='quote_file',
        ),
        migrations.AddField(
            model_name='quote',
            name='image_url',
            field=models.URLField(blank=True, editable=False, max_length=1024),
        ),
    ]
