# Generated by Django 4.2.7 on 2023-11-06 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0039_remove_quote_quote_file_quote_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='image_url',
            new_name='quote_url',
        ),
    ]
