# Generated by Django 4.2.7 on 2023-11-06 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0040_rename_image_url_quote_quote_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='s3_quote_key',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
