# Generated by Django 4.2.7 on 2023-11-06 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0041_quote_s3_quote_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='upload_status',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='product_image_model', to='materiah.fileuploadstatus'),
        ),
        migrations.AlterField(
            model_name='quote',
            name='upload_status',
            field=models.OneToOneField(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='quote_model', to='materiah.fileuploadstatus'),
        ),
    ]
