# Generated by Django 4.2.7 on 2023-11-06 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0042_alter_productimage_upload_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileuploadstatus',
            name='error_message',
        ),
        migrations.RemoveField(
            model_name='fileuploadstatus',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='fileuploadstatus',
            name='order_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiah.orderimage'),
        ),
        migrations.AddField(
            model_name='fileuploadstatus',
            name='product_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiah.productimage'),
        ),
        migrations.AddField(
            model_name='fileuploadstatus',
            name='quote',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiah.quote'),
        ),
    ]
