# Generated by Django 4.2.7 on 2023-11-06 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0043_remove_fileuploadstatus_error_message_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='upload_status',
        ),
        migrations.RemoveField(
            model_name='quote',
            name='upload_status',
        ),
    ]
