# Generated by Django 4.2.7 on 2023-11-06 20:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0044_remove_productimage_upload_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileuploadstatus',
            name='order_receipt',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiah.orderimage'),
        ),
        migrations.AlterField(
            model_name='fileuploadstatus',
            name='product_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiah.productimage'),
        ),
        migrations.AlterField(
            model_name='fileuploadstatus',
            name='quote',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiah.quote'),
        ),
    ]
