# Generated by Django 4.2.7 on 2023-11-06 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0045_alter_fileuploadstatus_order_receipt_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderimage',
            name='alt_text',
        ),
        migrations.RemoveField(
            model_name='orderimage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='orderimage',
            name='upload_status',
        ),
        migrations.AddField(
            model_name='orderimage',
            name='image_url',
            field=models.URLField(blank=True, editable=False, max_length=1024),
        ),
        migrations.AddField(
            model_name='orderimage',
            name='s3_image_key',
            field=models.CharField(default='null', max_length=255),
            preserve_default=False,
        ),
    ]
