# Generated by Django 4.2.7 on 2023-11-07 10:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0046_remove_orderimage_alt_text_remove_orderimage_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderimage',
            old_name='product',
            new_name='order',
        ),
    ]
