# Generated by Django 4.2.7 on 2023-11-07 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0047_rename_product_orderimage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='CronJobTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
