# Generated by Django 4.2.7 on 2023-11-08 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0048_cronjobtest'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CronJobTest',
        ),
    ]
