# Generated by Django 4.2.7 on 2023-11-11 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0049_delete_cronjobtest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('phone_prefix', 'phone_suffix')},
        ),
        migrations.AlterUniqueTogether(
            name='supplieruserprofile',
            unique_together={('contact_phone_prefix', 'contact_phone_suffix')},
        ),
        migrations.AlterUniqueTogether(
            name='userprofile',
            unique_together={('phone_prefix', 'phone_suffix')},
        ),
    ]
