# Generated by Django 4.2.7 on 2023-11-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0050_alter_supplier_email_alter_supplier_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='previous_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
