# Generated by Django 4.2.7 on 2024-01-04 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0052_remove_quoteitem_previous_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='volume',
            new_name='unit_quantity',
        ),
    ]
