# Generated by Django 4.2.7 on 2024-01-04 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0053_rename_volume_product_unit_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch', models.CharField(blank=True, max_length=50, null=True)),
                ('in_use', models.BooleanField(default=False)),
                ('expiry', models.DateField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='materiah.product')),
            ],
        ),
    ]
