# Generated by Django 4.2.7 on 2024-01-04 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0054_productitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_item',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='materiah.productitem'),
        ),
    ]
