# Generated by Django 4.2.7 on 2024-01-10 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0055_orderitem_product_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='product_item',
        ),
        migrations.AddField(
            model_name='productitem',
            name='order_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='materiah.orderitem'),
        ),
    ]
