# Generated by Django 4.2.7 on 2024-01-10 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0056_remove_orderitem_product_item_productitem_order_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quote',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='materiah.quote'),
        ),
    ]
