# Generated by Django 4.2.7 on 2024-01-15 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0057_alter_order_quote'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('L', 'Litres, l'), ('ML', 'Milliliters, ml'), ('KG', 'Kilograms, kg'), ('G', 'Grams, g'), ('MG', 'Milligrams, mg'), ('UG', 'Micrograms, µg'), ('Package', 'Package'), ('Box', 'Box')], max_length=50, verbose_name='measurement unit'),
        ),
    ]
