# Generated by Django 4.2.7 on 2024-01-17 08:11

from django.db import migrations, models
import materiah.models.custom_validators


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0059_alter_supplier_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='phone_prefix',
            field=models.CharField(blank=True, choices=[('050', '050'), ('051', '051'), ('052', '052'), ('053', '053'), ('054', '054'), ('055', '055'), ('056', '056'), ('058', '058'), ('059', '059'), ('02', '02'), ('03', '03'), ('04', '04'), ('05', '05'), ('08', '08'), ('09', '09'), ('071', '071'), ('072', '072'), ('073', '073'), ('074', '074'), ('076', '076'), ('077', '077'), ('079', '079')], default='02', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='phone_suffix',
            field=models.CharField(blank=True, max_length=7, null=True, validators=[materiah.models.custom_validators.validate_phone_suffix]),
        ),
    ]
