# Generated by Django 4.2.7 on 2024-01-22 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0062_alter_product_cat_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='productorderstatistics',
            name='avg_order_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiah.manufacturer'),
        ),
        migrations.CreateModel(
            name='ExpiryNotifications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_item', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='materiah.productitem')),
            ],
        ),
    ]
