# Generated by Django 4.2.7 on 2024-01-22 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0063_productorderstatistics_avg_order_quantity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productitem',
            name='order_item',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='materiah.orderitem'),
        ),
    ]
