# Generated by Django 4.2.7 on 2024-01-22 13:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0064_alter_productitem_order_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordernotifications',
            name='avg_order_time',
        ),
        migrations.RemoveField(
            model_name='ordernotifications',
            name='current_stock',
        ),
        migrations.RemoveField(
            model_name='ordernotifications',
            name='last_ordered',
        ),
        migrations.RemoveField(
            model_name='ordernotifications',
            name='product_cat_num',
        ),
        migrations.RemoveField(
            model_name='ordernotifications',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='ordernotifications',
            name='supplier_name',
        ),
    ]
