# Generated by Django 4.2.7 on 2024-01-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0065_remove_ordernotifications_avg_order_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='opened',
            field=models.DateField(blank=True, null=True),
        ),
    ]
