# Generated by Django 4.2.7 on 2024-01-24 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0066_productitem_opened'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productitem',
            name='opened',
        ),
        migrations.AddField(
            model_name='productitem',
            name='opened_on',
            field=models.DateField(blank=True, null=True),
        ),
    ]
