# Generated by Django 4.2.7 on 2024-01-24 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0067_remove_productitem_opened_productitem_opened_on'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='batch',
        ),
    ]
