# Generated by Django 4.2.7 on 2024-01-29 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0068_remove_orderitem_batch'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='expiry',
        ),
    ]
