# Generated by Django 4.2.7 on 2024-02-19 08:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('materiah', '0070_product_currency_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleCredentials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_id', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('client_secret', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('refresh_token', django_cryptography.fields.encrypt(models.CharField(max_length=255))),
                ('access_token', django_cryptography.fields.encrypt(models.CharField(max_length=255, null=True))),
                ('token_expiry', models.DateTimeField(null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='google_credentials', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
