# Generated by Django 4.2.7 on 2024-02-19 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0071_googlecredentials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='googlecredentials',
            name='client_id',
        ),
        migrations.RemoveField(
            model_name='googlecredentials',
            name='client_secret',
        ),
    ]
