# Generated by Django 4.2.7 on 2024-02-20 08:12

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0072_remove_googlecredentials_client_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googlecredentials',
            name='refresh_token',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=255, null=True)),
        ),
    ]
