# Generated by Django 4.2.7 on 2024-03-19 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0073_alter_googlecredentials_refresh_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='gmail_configured',
            field=models.BooleanField(default=False),
        ),
    ]
