# Generated by Django 4.2.7 on 2024-04-18 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0077_alter_product_location_alter_product_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='unit_quantity',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
    ]
