# Generated by Django 4.2.7 on 2024-04-24 12:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0079_suppliersecondaryemails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='suppliersecondaryemails',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secondary_emails', to='materiah.supplier'),
        ),
    ]
