# Generated by Django 4.2.7 on 2024-04-30 10:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0080_alter_suppliersecondaryemails_supplier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expirynotifications',
            name='product_item',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='materiah.productitem', unique=True),
        ),
    ]
