# Generated by Django 4.2.7 on 2024-05-13 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0085_product_units_per_main_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='productitem',
            name='item_stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
