# Generated by Django 4.2.7 on 2024-05-19 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0087_rename_units_per_main_unit_product_units_per_sub_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Matrix', 'Matrix'), ('Medium', 'Medium'), ('Supplement', 'Supplement'), ('Powder', 'Powder'), ('Enzyme', 'Enzyme'), ('Antibody', 'Antibody'), ('Dye', 'Dye'), ('Hormone', 'Hormone'), ('Medication', 'Medication'), ('Antibiotic', 'Antibiotic'), ('Kit', 'Kit'), ('Plastics', 'Plastics'), ('Glassware', 'Glassware'), ('Sanitary', 'Sanitary'), ('Lab Equipment', 'Lab Equipment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='storage',
            field=models.CharField(choices=[('+4', '+4'), ('-20', '-20'), ('-40', '-40'), ('-80', '-80'), ('Room Temperature', 'Room Temperature'), ('Other', 'Other')], max_length=20, verbose_name='storage conditions'),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('L', 'Litres, l'), ('ML', 'Milliliters, ml'), ('UL', 'Microliters, ml'), ('KG', 'Kilograms, kg'), ('G', 'Grams, g'), ('MG', 'Milligrams, mg'), ('UG', 'Micrograms, µg'), ('Reactions', 'Reactions'), ('Package', 'Package'), ('Box', 'Box')], max_length=50, verbose_name='measurement unit'),
        ),
    ]
