# Generated by Django 4.2.7 on 2024-06-05 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0088_alter_product_category_alter_product_storage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ProductItem',
            new_name='StockItem',
        ),
        migrations.RenameField(
            model_name='expirynotifications',
            old_name='product_item',
            new_name='stock_item',
        ),
        migrations.RenameField(
            model_name='stockitem',
            old_name='item_stock',
            new_name='item_sub_stock',
        ),
    ]
