# Generated by Django 4.2.7 on 2024-06-19 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0089_rename_productitem_stockitem_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Matrix', 'Matrix'), ('Medium', 'Medium'), ('Supplement', 'Supplement'), ('Powders', 'Powders'), ('Enzyme', 'Enzyme'), ('Antibody', 'Antibody'), ('Dye', 'Dye'), ('Hormone', 'Hormone'), ('Medication', 'Medication'), ('Antibiotic', 'Antibiotic'), ('Kit', 'Kit'), ('Plastics', 'Plastics'), ('Glassware', 'Glassware'), ('Sanitary', 'Sanitary'), ('Lab Equipment', 'Lab Equipment')], max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('L', 'Litres, l'), ('ML', 'Milliliters, ml'), ('UL', 'Microliters, ml'), ('KG', 'Kilograms, kg'), ('G', 'Grams, g'), ('MG', 'Milligrams, mg'), ('UG', 'Micrograms, µg'), ('Assays', 'Reactions/Tests/Assays'), ('Package', 'Package'), ('Box', 'Box')], max_length=50, verbose_name='measurement unit'),
        ),
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
