# Generated by Django 4.2.7 on 2024-06-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0092_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True),
        ),
    ]
