# Generated by Django 4.2.7 on 2024-06-23 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materiah', '0093_quoteitem_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoteitem',
            name='currency',
            field=models.CharField(blank=True, choices=[('NIS', 'NIS'), ('USD', 'USD'), ('EUR', 'EUR')], max_length=20, null=True, verbose_name='currency'),
        ),
    ]
